### PR TITLE
Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by marcin-jelenski**
Hi,

let's remove big guava dependency as it's used only for `@AutoService`. It can be replaced with a single line in `META-INF` directory.

I removed also unused test dependencies. Will they be used in your future work?

Best regards,
Marcin

### CODE REVIEW

**Comment by blipinsk** [comment]
Hi Marcin, 
I'd rather keep `AutoService` as an annotation as this feels much more straightforward to me. Having guava for a dependency in compiler doesn't matter that much since the compiler code will not be packed within your app.

If you don't like the fact that the testing dependencies are there we can remove them. I will be improving `dagger2-ktx` soon, so they might come in handy, but for now they are useless.

Let me know if you want to improve the PR or leave the testing dependencies for now.

Thanks!

P.S. Sorry for the late response, you've send the PR at the beginning of my holidays 😊

**Comment by marcin-jelenski** [comment]
Hi Bartek,

Of course it won't be packaged, but there's a chance of version collision. It may affect users if they use legacy guava even as a transitive dependency.
Worth considering as dagger-ktx is a candidate for a library rather than a sample and it can cause unneccessary maintenance issues in the future.

Let's leave the testing dependencies until your future tests. I used kaptAndroidTest to run end-to-end tests of code generation in some of my projects - it works quite well, you might try this instead of google's compile-testing which is quite buggy: https://github.com/google/compile-testing/issues

And one more thing: is there any reason why you're keeping Dagger2KtxProcessor in Java? It still works after conversion to Kotlin.

Don't worry about the late response, it was not urgent :)

**Comment by blipinsk** [comment]
> Of course it won't be packaged, but there's a chance of version collision. It may affect users if they use legacy guava even as a transitive dependency.

Can you give me an example of such collision? Wouldn't that have to be a collision between annotation processors?

>  I used kaptAndroidTest to run end-to-end tests of code generation in some of my projects - it works quite well, you might try this instead of google's compile-testing

I would love to hear more about that! I used compile-testing multiple times without any issues, but the problem here is that it is for java source files. Even if I make it work with kotlin files it would be essentially testing kotlin cross converted to java.

> And one more thing: is there any reason why you're keeping Dagger2KtxProcessor in Java? It still works after conversion to Kotlin.

I had issues with the processor being "detected" during compilation when it was in Kotlin. Maybe using the META-INF would solve that...

**Comment by pchmielowski** [comment]
> I had issues with the processor being "detected" during compilation when it was in Kotlin. Maybe using the META-INF would solve that...

I think `AutoService` does not support Kotlin. However there is a simple method to keep files in Kotlin - `Dagger2KtxProcessor` can be an `open` class (in Kotlin), and `Dagger2KtxProcessorShim` can be created in Java. This class can extend `Dagger2KtxProcessor` and be annotated with `@AutoService(Processor.class)` annotation.

**Pull request closed without merging**
